# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 10:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='The short description for that element', max_length=200, verbose_name='Description')),
                ('annotation', models.TextField(help_text='Here you can give more deep information', verbose_name='Annotation')),
                ('creation_date', models.DateField(auto_now_add=True, help_text='When the element was created', verbose_name='Creation Date')),
                ('edit_date', models.DateField(auto_now=True, help_text='When the element was modified last time', verbose_name='Edit Date')),
                ('creation_user', models.TextField(help_text='Who created the element', verbose_name='Creation User')),
                ('edit_user', models.TextField(help_text='Who modified the element last time', verbose_name='Edit User')),
                ('start_date', models.DateField(help_text='When project should start', verbose_name='Start Date')),
                ('end_date', models.DateField(help_text='When project should end', verbose_name='End Date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='The short description for that element', max_length=200, verbose_name='Description')),
                ('annotation', models.TextField(help_text='Here you can give more deep information', verbose_name='Annotation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.ForeignKey(help_text='The progression state of the project', on_delete=django.db.models.deletion.CASCADE, related_name='project_state', to='project.ProjectState', verbose_name='State'),
        ),
        migrations.AddField(
            model_name='project',
            name='supervisor',
            field=models.ForeignKey(help_text='Who is the project supervisor', on_delete=django.db.models.deletion.CASCADE, related_name='project_supervisor', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor'),
        ),
    ]
