# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='creation_user',
            field=models.CharField(help_text='Who created the element', max_length=200, verbose_name='Creation User'),
        ),
        migrations.AlterField(
            model_name='project',
            name='edit_user',
            field=models.CharField(help_text='Who modified the element last time', max_length=200, verbose_name='Edit User'),
        ),
    ]
