# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 12:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20170510_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='annotation',
            field=models.TextField(blank=True, help_text='Here you can give more deep information', verbose_name='Annotation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='creation_user',
            field=models.CharField(blank=True, help_text='Who created the element', max_length=200, verbose_name='Creation User'),
        ),
        migrations.AlterField(
            model_name='project',
            name='edit_user',
            field=models.CharField(blank=True, help_text='Who modified the element last time', max_length=200, verbose_name='Edit User'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, help_text='When project should end', verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, help_text='When project should start', verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.ForeignKey(blank=True, help_text='The progression state of the project', on_delete=django.db.models.deletion.CASCADE, related_name='project_state', to='project.ProjectState', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='project',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Who is the project supervisor', on_delete=django.db.models.deletion.CASCADE, related_name='project_supervisor', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor'),
        ),
        migrations.AlterField(
            model_name='projectstate',
            name='annotation',
            field=models.TextField(blank=True, help_text='Here you can give more deep information', verbose_name='Annotation'),
        ),
    ]
