# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 12:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20170510_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, help_text='When project should end', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, help_text='When project should start', null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.ForeignKey(blank=True, help_text='The progression state of the project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_state', to='project.ProjectState', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='project',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Who is the project supervisor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_supervisor', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor'),
        ),
    ]
