# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-26 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('project', '0004_auto_20170510_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Owning group', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_group', to='group.ProjectGroup', verbose_name='Group'),
        ),
    ]
