# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20170510_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='annotation',
            field=models.TextField(blank=True, help_text='Here you can give more deep information', verbose_name='Annotation'),
        ),
        migrations.AlterField(
            model_name='task',
            name='creation_user',
            field=models.CharField(blank=True, help_text='Who created the element', max_length=200, verbose_name='Creation User'),
        ),
        migrations.AlterField(
            model_name='task',
            name='edit_user',
            field=models.CharField(blank=True, help_text='Who modified the element last time', max_length=200, verbose_name='Edit User'),
        ),
        migrations.AlterField(
            model_name='taskpriority',
            name='annotation',
            field=models.TextField(blank=True, help_text='Here you can give more deep information', verbose_name='Annotation'),
        ),
        migrations.AlterField(
            model_name='taskprogression',
            name='annotation',
            field=models.TextField(blank=True, help_text='Here you can give more deep information', verbose_name='Annotation'),
        ),
    ]
