# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 13:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20170510_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Who is executing the task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_assignee', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_on',
            field=models.DateField(blank=True, help_text='When task was completed', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_to',
            field=models.DateField(blank=True, help_text='When task has to be completed', null=True, verbose_name='Due To'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.ForeignKey(blank=True, help_text='How the task is urgent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_priority', to='task.TaskPriority', verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='task',
            name='progression',
            field=models.ForeignKey(blank=True, help_text='What is the progression state of the task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_progression', to='task.TaskProgression', verbose_name='Proression'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, help_text='The project that is the task owner', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_project_owner', to='project.Project', verbose_name='Project'),
        ),
    ]
