# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20170510_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='progression',
            field=models.ForeignKey(blank=True, help_text='What is the progression state of the task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_progression', to='task.TaskProgression', verbose_name='Progression'),
        ),
    ]
