# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='The short description for that element', max_length=200, verbose_name='Description')),
                ('annotation', models.TextField(help_text='Here you can give more deep information', verbose_name='Annotation')),
                ('creation_date', models.DateField(auto_now_add=True, help_text='When the element was created', verbose_name='Creation Date')),
                ('edit_date', models.DateField(auto_now=True, help_text='When the element was modified last time', verbose_name='Edit Date')),
                ('creation_user', models.TextField(help_text='Who created the element', verbose_name='Creation User')),
                ('edit_user', models.TextField(help_text='Who modified the element last time', verbose_name='Edit User')),
                ('completed_on', models.DateField(help_text='When sub task was completed', verbose_name='Completed Date')),
                ('task', models.ForeignKey(help_text='The owner task', on_delete=django.db.models.deletion.CASCADE, related_name='task_owner', to='task.Task', verbose_name='Task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
