# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtask', '0004_auto_20170519_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='completed',
            field=models.BooleanField(default=False, help_text='If sub task was completed', verbose_name='Completed'),
        ),
    ]
